GET  http://localhost:3000/api/usuario

###

POST http://localhost:3000/api/usuario/2
Content-Type: application/json

{
    "nombre_usuario": "user1",
    "contrasenia": "user123"
}

###

PATCH http://localhost:3000/api/usuario/1
Content-Type: application/json

{
    "contrasenia": "hola123"
}

###

DELETE http://localhost:3000/api/usuario/4

###

POST http://localhost:3000/api/usuario/login
Content-Type: application/json

{
    "nombre_usuario": "admin",
    "contrasenia": "admin123"
}