GET http://localhost:3000/api/mascota
###
POST http://localhost:3000/api/mascota/duenio/6
Content-Type: application/json

{
    "nombre_mascota": "aniangaseio montes",
    "especie": "Gato",
    "raza": "Siames",
    "castrado": true,
    "sexo": "F",
    "fechaNac": "2015-01-01"
}
###
GET http://localhost:3000/api/mascota/duenio/6

###
PATCH http://localhost:3000/api/mascota/2
Content-Type: application/json

{
    "especie": "modificaod"
}

###

DELETE http://localhost:3000/api/mascota/2